### ISSUE TITLE
Delegación de responsabilidades

### ISSUE THREAD

**Issue by Chamejul** [Chamejul/TrabajoFinalAlgo#1]

**Comment by Chamejul** [comment]
Creación del documento del hito1

**Comment by KaozAngel** [comment]
https://docs.google.com/document/d/1T-z-1Vatz00RaN2rFoAkT2ME8sAj7AyYOAPd9W2HhJQ/edit

**Comment by KaozAngel** [comment]
https://docs.google.com/document/d/1T-z-1Vatz00RaN2rFoAkT2ME8sAj7AyYOAPd9W2HhJQ/edit?usp=sharing
